public enum TokenTypes {
    LPAREN, RPAREN, LBRACE, RBRACE, COMMA, SEMICOLON, IF,
    ELSE, VAR, PRINT, WHILE, BREAK, FUN, RETURN, INT, DECIMAL, STRING, BOOLEAN, EQUAL, NOT_EQUAL, PLUS,
    MINUS, MULTIPLY, DIVIDE, ASSIGN, LINE_COMMENT, BLOCK_COMMENT, NAME,
    EOF, WHITE_SPACE,
}
